import Link from 'next/link';
import { ArrowRight, Database, SearchCode } from 'lucide-react';


const translations = {
  en: {
    comparisonLabel: 'Choose by',
    dataFlowLabel: 'Data flow',
    flowLabels: ['Index', 'Search'],
    flows: [
      [
        ['Schema', 'Parsed records + vectors', 'insert / upsert', 'Indexes'],
        ['Vector / text / filters', 'query()', 'Ranked documents'],
      ],
      [
        ['Workspace files', 'Scan + parse + chunk', 'BM25 + vector index'],
        ['Query', 'Exact / hybrid', 'CLI / MCP', 'Human / agent'],
      ],
    ],
    comparisons: [
      {
        label: 'Typical scenarios',
        zvec: [
          'Store and query embeddings generated by your application',
          'Index parsed records with text, vectors, and scalar metadata',
          'Control schemas, indexes, filters, and hybrid queries in code',
        ],
        grep: [
          'Search a code or document workspace as it already exists',
          'Let Zvec-Grep scan, parse, chunk, embed, and index the files',
          'Retrieve workspace evidence from the CLI or an AI agent',
        ],
      },
      {
        label: 'Use through',
        zvec: 'Native SDKs',
        grep: 'CLI, MCP, or AI agents',
      },
      {
        label: 'Choose it when',
        zvec: 'You own data parsing and vector generation and need a programmable retrieval engine',
        grep: 'You want ready-to-use workspace search without implementing ingestion or retrieval',
      },
    ],
    products: [
      {
        label: 'Embedded retrieval',
        title: 'Zvec',
        href: '/docs/db/',
      },
      {
        label: 'Workspace search',
        title: 'Zvec-Grep',
        href: '/docs/zvec-grep/',
      },
    ],
  },
  zh: {
    comparisonLabel: '对比维度',
    dataFlowLabel: '数据链路',
    flowLabels: ['建索引', '检索'],
    flows: [
      [
        ['Schema', '已解析记录与向量', 'insert / upsert', '索引'],
        ['向量 / 文本 / 过滤', 'query()', '排序结果'],
      ],
      [
        ['工作区文件', '扫描、解析与分块', 'BM25 + 向量索引'],
        ['查询', '精确 / 混合', 'CLI / MCP', '用户 / Agent'],
      ],
    ],
    comparisons: [
      {
        label: '典型场景',
        zvec: [
          '存储并查询由应用生成的 Embedding',
          '索引已解析的文本、向量与标量元数据',
          '在代码中控制 Schema、索引、过滤与混合查询',
        ],
        grep: [
          '直接检索现有代码或文档工作区',
          '由 Zvec-Grep 完成扫描、解析、分块、Embedding 与索引',
          '通过 CLI 或 AI Agent 获取工作区证据',
        ],
      },
      {
        label: '使用方式',
        zvec: '原生 SDK',
        grep: 'CLI、MCP 或 AI Agent',
      },
      {
        label: '选择依据',
        zvec: '自行负责数据解析与向量生成，并需要可编程的检索引擎',
        grep: '希望开箱即用地检索工作区，无需实现摄取与检索链路',
      },
    ],
    products: [
      {
        label: '嵌入式检索引擎',
        title: 'Zvec',
        href: '/docs/db/',
      },
      {
        label: '本地工作区搜索',
        title: 'Zvec-Grep',
        href: '/docs/zvec-grep/',
      },
    ],
  },
};


export default function DocsOverview({ lang }: { lang: string }) {
  const currentLang = lang === 'zh' ? 'zh' : 'en';
  const t = translations[currentLang];
  const icons = [Database, SearchCode];
  const localize = (href: string) => `/${currentLang}${href}`;

  return (
    <div className="zvec-docs-overview">
      <div className="zvec-docs-choice-table-wrap">
        <table className="zvec-docs-choice-table">
          <colgroup>
            <col className="zvec-docs-choice-axis" />
            <col />
            <col />
          </colgroup>
          <thead>
            <tr>
              <th>{t.comparisonLabel}</th>
              {t.products.map((product, index) => {
                const Icon = icons[index];
                return (
                  <th scope="col" key={product.title}>
                    <Link className="zvec-docs-choice-product" href={localize(product.href)}>
                      <span className="zvec-docs-overview-icon"><Icon aria-hidden="true" /></span>
                      <span>
                        <small>{product.label}</small>
                        <strong>{product.title}</strong>
                      </span>
                    </Link>
                  </th>
                );
              })}
            </tr>
          </thead>
          <tbody>
            {t.comparisons.map((comparison) => (
              <tr key={comparison.label}>
                <th scope="row">{comparison.label}</th>
                {[comparison.zvec, comparison.grep].map((value, index) => (
                  <td key={index}>
                    {Array.isArray(value) ? (
                      <ul className="zvec-docs-scenario-list">
                        {value.map((item) => <li key={item}>{item}</li>)}
                      </ul>
                    ) : value}
                  </td>
                ))}
              </tr>
            ))}
            <tr>
              <th scope="row">{t.dataFlowLabel}</th>
              {t.flows.map((flow, flowIndex) => (
                <td key={t.products[flowIndex].title}>
                  <div className="zvec-docs-data-flow">
                    {flow.map((steps, laneIndex) => (
                      <div className="zvec-docs-data-flow-lane" key={t.flowLabels[laneIndex]}>
                        <strong>{t.flowLabels[laneIndex]}</strong>
                        <div>
                          {steps.map((step, stepIndex) => (
                            <span className="zvec-docs-data-flow-step" key={step}>
                              <span>{step}</span>
                              {stepIndex < steps.length - 1 && <ArrowRight aria-hidden="true" />}
                            </span>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </td>
              ))}
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}
